sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download and install sdk in travis CLI
  - source $HOME/google-cloud-sdk/path.bash.inc # apply additional configuration
  - gcloud components update kubectl # update ikubectl nside travis environment
  - gcloud auth activate-service-account --key-file service-account.json # passing file with credentials
