apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: anithalysecretname
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: anithaly.com
  dnsNames:
    - anithaly.com
    - www.anithaly.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - anithaly.com
          - www.anithaly.com
