apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: # additional config options for the object
    kubernetes.io/ingress.class: nginx # create ingress controller based on nginx project
     # our nginx behavior
    # rewrite on request
    # example: rewrite /api to just /
    # nginx.ingress.kubernetes.io/rewrite-target: / # old way
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    certmanager.k8s.io/cluster-issuer: 'letsencrypt-prod' # expect certificate from the lets encrypt issuer
    nginx.ingress.kubernetes.io/ssl-redirect: 'true' # redirect to https always
spec:
  tls:
    - hosts:
        - anithaly.com
        - www.anithaly.com
      secretName: anithalysecretname
  rules:
    # for anithaly.com
    - host: anithaly.com
      http:
        paths: # 2 possible paths (routes)
          - path: /?(.*) # / send to pods govern by the service client-cluster-ip-service
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*) # /api send to pods govern by the service server-cluster-ip-service
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    # for www.anithaly.com
    - host: www.anithaly.com
      http:
        paths: # 2 possible paths (routes)
          - path: /?(.*) # / send to pods govern by the service client-cluster-ip-service
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*) # /api send to pods govern by the service server-cluster-ip-service
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
