apiVersion: apps/v1
kind: Deployment # object of type Deployment
metadata:
  name: server-deployment # name of deployment
spec: # configure this Deployment and its behaviour
  replicas: 3
  selector:
    matchLabels:
      component: server
  template: # pod template for server
    metadata:
      labels:
        component: server # identify pods it is supposed to manage
    spec: # behaviours of created pods
      containers: # containers in this pod
        - name: server
          image: nataliastanko/multi-server-fib
          ports: # ports we want to make available
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: 6379
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: 5432
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword #from kubectl get secrets
                  key: PGPASSWORD #from kubectl create secret generic pgpassword --from-literal PGPASSWORD=yourpassword
